'use client';
import {useState,type FormEvent} from 'react';
import {ArrowDown,ArrowUpRight,MapPin,Heart,Check,PawPrint,Sun,Clock,Utensils,Leaf} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {RSVP_ENDPOINT} from '@/lib/config';
const map='https://www.google.com/maps/search/?api=1&query=The+White+Barn+HK+351+Shui+Mei+Tsuen';
const image=(n:string)=>`./images/${n}.jpg`;
function Choices({value,onChange,options,name}:{value:string,onChange:(v:string)=>void,options:string[],name:string}){return <RadioGroup aria-label={name} value={value} onValueChange={v=>onChange(String(v))} className="choices">{options.map(o=><label key={o} className={value===o?'choice selected':'choice'}><RadioGroupItem value={o}/>{o}</label>)}</RadioGroup>}
export default function Home(){
const [attend,setAttend]=useState('出席'),[events,setEvents]=useState('證婚及午宴'),[transport,setTransport]=useState('自行前往'),[consent,setConsent]=useState(false),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('');if(!consent){setStatus('請先同意婚禮聯絡所需的資料收集。');return;}if(!RSVP_ENDPOINT){setStatus('出席回覆尚未開放，請稍後再試，或直接聯絡 Sophia / Kaiho。');return;}const data=new FormData(e.currentTarget);const adults=attend==='出席'?Number(data.get('adults')):0,children=attend==='出席'?Number(data.get('children')):0;if(attend==='出席'&&adults+children<1){setStatus('出席總人數至少為 1 人。');return;}let id='';try{id=localStorage.getItem('sk-rsvp-id')||crypto.randomUUID();localStorage.setItem('sk-rsvp-id',id);}catch{id=crypto.randomUUID();}const payload={id,name:String(data.get('name')||'').trim(),phone:String(data.get('phone')||'').trim(),attend,adults,children,events,transport,pets:attend==='出席'?Number(data.get('pets')):0,diet:String(data.get('diet')||''),note:String(data.get('note')||''),consent:true,website:String(data.get('website')||'')};setBusy(true);try{const res=await fetch(RSVP_ENDPOINT,{method:'POST',body:JSON.stringify(payload),headers:{'Content-Type':'text/plain;charset=utf-8'},signal:AbortSignal.timeout(25000)});const result=await res.json();if(!res.ok||!result.ok)throw new Error();setDone(true);setStatus('你的回覆已成功記錄。多謝你，期待與你分享這一天！');}catch{setStatus('暫時未能確認回覆，請重新提交。同一裝置重試會更新同一份回覆，不會重複計算。');}finally{setBusy(false);}}
return <><a className="skip" href="#main">跳至內容</a><header className="nav"><a className="monogram" href="#home">S <span>&</span> K</a><nav aria-label="主選單"><a href="#story">我們的故事</a><a href="#day">婚禮詳情</a><a href="#venue">地點交通</a><a className="nav-rsvp" href="#rsvp">回覆出席 <ArrowUpRight size={15}/></a></nav></header><main id="main">
<section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">TOGETHER, A NEW CHAPTER</p><h1>Sophia <span>&</span><br/>Kaiho</h1><p className="hero-chinese">從同窗，到一生。</p><div className="date"><span>20</span><i/><div>FEBRUARY 2027<br/><small>星期六 · 2027 年 2 月 20 日</small></div></div><p className="hero-venue">THE WHITE BARN HK</p><a className="button" href="#rsvp">與我們一起，見證幸福 <ArrowUpRight size={17}/></a><a className="scroll-link" href="#story">我們的故事 <ArrowDown size={14}/></a></div><div className="hero-photo"><img src={image('cover')} alt="Sophia 與 Kaiho 在綠樹草地間牽手回望" fetchPriority="high"/><span className="photo-caption">You, me & all the days to come.</span></div><div className="vertical-note">THE WEDDING OF SOPHIA & KAIHO</div></section>
<section className="invitation"><img src={image('botanical')} alt="" loading="lazy"/><div><p className="eyebrow">WE'RE GETTING MARRIED</p><h2>在綠意與微風之間，<br/>把往後的日子，交給彼此。</h2><p>誠邀最親愛的你，在這個溫暖的午前，<br/>與我們一起，讓熟悉的故事寫下新的篇章。</p></div></section>
<section id="story" className="story section"><div className="story-photo"><img src={image('story')} alt="Sophia 與 Kaiho 穿校服站在校園球場" loading="lazy"/><span className="small-caption">從校園開始的我們</span></div><div className="story-copy"><p className="eyebrow">01 / OUR STORY</p><h2>原來，一直是你。</h2><p>我們相識於微時，從小學、中學到大學，在彼此的青春裡，留下了同一段風景。</p><p>小學頒獎禮上的一面之緣，是故事悄悄埋下的伏筆。後來，在校園電視台並肩忙碌的日子裡，話題漸多，默契漸深；走過中學時的高低起跌，我們終於從同學，成為彼此最特別的人。</p><p>此後，我們牽著手走訪不同國家，收集沿途的風景，也在平凡日常中學會陪伴。回頭才發現，最喜歡的旅程，是一路都有你。</p><p className="story-last">如今，我們準備踏上人生的新階段。<br/>下一站，是有彼此的每一天。</p><span className="signature">Sophia & Kaiho</span></div></section>
<section className="day section" id="day"><p className="eyebrow">02 / THE WEDDING DAY</p><h2>那一天，與你相聚。</h2><p className="section-sub">2027 年 2 月 20 日・星期六</p><div className="timeline">{[[Clock,'10:00','AM','賓客簽到','早一點到，聊聊天、拍拍照。'],[Heart,'11:00','AM','戶外證婚','在草地上，見證我們的承諾。'],[Utensils,'12:30','PM','自助午宴','一起享用美食，分享這份喜悅。']].map(([Icon,time,period,title,desc])=>{const I=Icon as typeof Clock;return <article key={String(time)}><I strokeWidth={1}/><p className="time">{String(time)}<span>{String(period)}</span></p><h3>{String(title)}</h3><p>{String(desc)}</p></article>})}</div><p className="day-note">午宴以自助餐形式進行。歡迎在回覆時告訴我們飲食及過敏需要。</p></section>
<section className="venue section" id="venue"><div><p className="eyebrow">03 / A PLACE TO CELEBRATE</p><h2>The White Barn HK</h2><p className="address"><MapPin size={18}/>新界元朗錦田水尾村 351 號</p><p>草地、樹影與開闊的天空，<br/>是我們想與你分享的婚禮風景。</p><p className="pet-tag"><PawPrint size={16}/> 寵物友善場地 · 歡迎毛孩同行</p><a className="text-link" href={map} target="_blank" rel="noreferrer">在 Google Maps 查看路線 <ArrowUpRight size={17}/></a><div className="transport"><h3>交通安排</h3><p>接駁車安排及集合時間將於稍後公布。請在回覆中告訴我們你的交通意向，方便統籌。</p><p>自行駕車的親友，請先與我們確認泊車安排及車位。出發前可使用 Google Maps 規劃路線，並預留充足時間。</p></div></div><iframe title="The White Barn HK Google 地圖" src="https://maps.google.com/maps?q=The%20White%20Barn%20HK%20351%20Shui%20Mei%20Tsuen&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></section>
<section className="notes section" id="notes"><p className="eyebrow">04 / A FEW LITTLE NOTES</p><h2>讓這一天，更自在。</h2><div className="note-grid"><article><Leaf/><h3>草地上的穿搭</h3><p>歡迎清新、輕便而得體的半正式穿搭。平底鞋、粗跟鞋或坡跟鞋較適合草地；避免幼跟及容易陷入泥土的鞋款，或配備鞋跟保護套。選擇防滑鞋底，裙襬不宜拖地，方便走動與拍照。</p></article><article><Sun/><h3>戶外的小準備</h3><p>二月戶外可能較涼，建議帶上薄外套或披肩，亦可準備防曬及防蚊用品。如天氣影響戶外儀式，我們會另行通知最新安排。</p></article><article><Utensils/><h3>一起享用午宴</h3><p>婚宴為午間自助餐。若有素食、食物敏感或其他飲食需要，請在回覆時註明，讓我們提早與餐飲團隊協調。</p></article><article><PawPrint/><h3>毛孩也是家人</h3><p>歡迎帶毛孩來分享喜悅，請先在回覆中登記數目。建議準備牽繩、飲水及清潔用品，照顧毛孩之餘，也讓其他賓客舒適自在。入場細節以場地安排為準。</p></article></div></section>
<section className="memories"><figure><img src={image('joy')} alt="兩人在遊樂場滑梯上開懷大笑" loading="lazy"/><figcaption>一起笑，一起長大。</figcaption></figure><figure><img src={image('snow')} alt="Sophia 與 Kaiho 在小樽雪地牽手散步" loading="lazy"/><figcaption>走過四季，身邊仍然是你。</figcaption></figure></section>
<section className="rsvp section" id="rsvp"><div className="rsvp-intro"><p className="eyebrow">05 / RSVP</p><h2>這一天，<br/>想留一個位置給你。</h2><p>請以一組親友為單位填寫，<br/>讓我們為你和同行的家人朋友作好安排。</p><p className="fine">已提交的回覆可於同一裝置重新填寫更新；如轉用其他裝置或需要協助，請直接聯絡我們。</p><img src={image('botanical')} alt="" loading="lazy"/></div><form onSubmit={submit} className="rsvp-form">{done?<div className="success" role="status"><Check/><h3>收到你的心意了。</h3><p>{status}</p><button type="button" className="text-link" onClick={()=>{setDone(false);setStatus('')}}>修改回覆 <ArrowUpRight size={16}/></button></div>:<><div className="two-fields"><label>姓名 *<Input name="name" required maxLength={80} autoComplete="name" placeholder="方便我們稱呼你"/></label><label>WhatsApp 電話 *<Input name="phone" type="tel" required minLength={8} maxLength={24} autoComplete="tel" placeholder="例如 +852 9123 4567"/></label></div><fieldset><legend>你能出席嗎？ *</legend><Choices name="出席意願" value={attend} onChange={setAttend} options={['出席','未能出席']}/></fieldset>{attend==='出席'&&<><fieldset><legend>參與環節 *</legend><Choices name="參與環節" value={events} onChange={setEvents} options={['證婚及午宴','只出席證婚','只出席午宴']}/></fieldset><div className="two-fields"><label>成人（包括自己） *<Input type="number" name="adults" defaultValue={1} min={0} max={30} step={1} required/></label><label>小童（包括嬰幼兒） *<Input type="number" name="children" defaultValue={0} min={0} max={30} step={1} required/></label></div><p className="fine">以上人數將用於你選擇的所有環節。如各環節人數不同，請在備註註明，讓我們跟進。</p><fieldset><legend>交通意向 *</legend><Choices name="交通意向" value={transport} onChange={setTransport} options={['自行前往','希望乘坐接駁車','自行駕車','尚未決定']}/></fieldset><label>同行寵物數目<Input type="number" name="pets" defaultValue={0} min={0} max={10} step={1} required/></label><label>飲食及過敏需要<Textarea name="diet" maxLength={1000} placeholder="例如：1 位素食、1 位對花生敏感"/></label></>}<label>備註／想對我們說的話<Textarea name="note" maxLength={1500} placeholder="同行親友姓名、特別安排，或送給我們的祝福⋯⋯"/></label><div className="honeypot" aria-hidden="true"><label>Website<Input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(Boolean(v))}/><span>我同意 Sophia 與 Kaiho 收集上述資料，僅用於婚禮出席統計及相關聯絡。回覆不會公開展示。</span></label>{status&&<p role="alert" className="error">{status}</p>}<button className="button submit" disabled={busy} type="submit">{busy?'正在確認你的回覆⋯':'送出回覆'}<ArrowUpRight size={18}/></button></>}</form></section>
</main><footer><span className="signature">Sophia & Kaiho</span><p>20.02.2027 · THE WHITE BARN HK</p><p>期待，與你相見。</p><a href="#home">回到頂部 ↑</a></footer><a className="mobile-rsvp" href="#rsvp">回覆出席 <ArrowUpRight size={16}/></a></>;
}
