'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {ArrowDown,ArrowUpRight,MapPin,Heart,Check,PawPrint,Sun,Clock,Utensils,Leaf} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {RSVP_ENDPOINT} from '@/lib/config';
const map='https://www.google.com/maps/search/?api=1&query=The+White+Barn+HK+351+Shui+Mei+Tsuen';
const image=(n:string)=>`./images/${n}.jpg`;
function Choices({value,onChange,options,name}:{value:string,onChange:(v:string)=>void,options:string[],name:string}){return <RadioGroup aria-label={name} value={value} onValueChange={v=>onChange(String(v))} className="choices">{options.map(o=><label key={o} className={value===o?'choice selected':'choice'}><RadioGroupItem value={o}/>{o}</label>)}</RadioGroup>}
function Countdown(){
const [seconds,setSeconds]=useState<number|null>(null);
useEffect(()=>{const tick=()=>setSeconds(Math.max(0,Math.floor((Date.parse('2027-02-20T10:00:00+08:00')-Date.now())/1000)));tick();const timer=setInterval(tick,1000);return()=>clearInterval(timer)},[]);
return <div className="countdown" aria-label="距離婚禮開始的倒數時間"><p>距離我們的大日子</p><div>{[Math.floor((seconds??0)/86400),Math.floor((seconds??0)%86400/3600),Math.floor((seconds??0)%3600/60),(seconds??0)%60].map((n,i)=><span key={i}><strong>{seconds===null?'—':String(n).padStart(2,'0')}</strong><small>{['天','時','分','秒'][i]}</small></span>)}</div></div>;
}
export default function Home(){
const [side,setSide]=useState(''),[attend,setAttend]=useState('出席'),[events,setEvents]=useState('證婚及午宴'),[transport,setTransport]=useState('自行前往'),[consent,setConsent]=useState(false),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[done,setDone]=useState(false);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setStatus('');if(!side){setStatus('請選擇您是男家或女家的親友。');return;}if(!consent){setStatus('請先同意婚禮聯絡所需的資料收集。');return;}if(!RSVP_ENDPOINT){setStatus('出席回覆尚未開放，請稍後再試，或直接聯絡 Sophia / Kaiho。');return;}const data=new FormData(e.currentTarget);const adults=attend==='出席'?Number(data.get('adults')):0,children=attend==='出席'?Number(data.get('children')):0;if(attend==='出席'&&adults+children<1){setStatus('出席總人數至少為 1 人。');return;}let id='';try{id=localStorage.getItem('sk-rsvp-id')||crypto.randomUUID();localStorage.setItem('sk-rsvp-id',id);}catch{id=crypto.randomUUID();}const payload={id,side,name:String(data.get('name')||'').trim(),phone:String(data.get('phone')||'').trim(),attend,adults,children,events,transport,pets:attend==='出席'?Number(data.get('pets')):0,diet:String(data.get('diet')||''),note:String(data.get('note')||''),consent:true,website:String(data.get('website')||'')};setBusy(true);try{const res=await fetch(RSVP_ENDPOINT,{method:'POST',body:JSON.stringify(payload),headers:{'Content-Type':'text/plain;charset=utf-8'},signal:AbortSignal.timeout(25000)});const result=await res.json();if(!res.ok||!result.ok)throw new Error();setDone(true);setStatus('您的回覆已成功記錄。多謝您，期待與您分享這一天！');}catch{setStatus('暫時未能確認回覆，請重新提交。同一裝置重試會更新同一份回覆，不會重複計算。');}finally{setBusy(false);}}
return <><a className="skip" href="#main">跳至內容</a><header className="nav"><a className="monogram" href="#home">S <span>&</span> K</a><nav aria-label="主選單"><a href="#story">我們的故事</a><a href="#day">婚禮詳情</a><a href="#venue">地點交通</a><a className="nav-rsvp" href="#rsvp">回覆出席 <ArrowUpRight size={15}/></a></nav></header><main id="main">
<section className="hero" id="home"><div className="hero-copy"><p className="eyebrow">TOGETHER, A NEW CHAPTER</p><h1>Sophia <span>&</span><br/>Kaiho</h1><div className="date"><span>20</span><i/><div>FEBRUARY 2027<br/><small>2027 年 2 月 20 日・星期六</small></div></div><p className="hero-venue">THE WHITE BARN HK</p><Countdown/><a className="button" href="#rsvp">回覆出席 <ArrowUpRight size={17}/></a><a className="scroll-link" href="#story">我們的故事 <ArrowDown size={14}/></a></div><div className="hero-photo"><img src={image('cover')} alt="Sophia 與 Kaiho 在綠樹草地間牽手回望" fetchPriority="high"/><span className="photo-caption">You, me & all the days to come.</span></div><div className="vertical-note">THE WEDDING OF SOPHIA & KAIHO</div></section>
<section id="story" className="story section"><div className="story-photo"><img src={image('story')} alt="Sophia 與 Kaiho 穿校服站在校園球場" loading="lazy"/></div><div className="story-copy"><p className="eyebrow">01 / OUR STORY</p><h2>從同窗，到一生</h2><div className="story-chinese" lang="zh-Hant"><article><h3>2006 / 相遇</h3><p>在小學相識，因校園活動漸漸熟悉。<br/>彼此的故事，也在不知不覺間開始。</p></article><article><h3>2016 / 相知</h3><p>從小學到中學，我們一起走過青春。<br/>這一年，我們從同學成為戀人。</p></article><article><h3>2016–2027 / 相伴</h3><p>一起升讀大學、踏入社會，也攜手看過不同地方的風景。<br/>在歲月流轉中，我們學會理解、珍惜與陪伴。</p></article><article><h3>2027 / 相守</h3><p>走過二十多年的相識與相伴，我們攜手走進婚姻。<br/>往後的每一天，都有彼此。</p></article></div><span className="signature">Sophia & Kaiho</span></div></section>
<figure className="mobile-only day-photo-divider"><img src={image('joy')} alt="兩人在遊樂場滑梯上開懷大笑" loading="lazy"/></figure><section className="day section" id="day"><p className="eyebrow">02 / THE WEDDING DAY</p><h2 className="day-heading"><span>誠摯邀請您，</span><span>見證我們的重要時刻。</span></h2><p className="section-sub">2027 年 2 月 20 日・星期六</p><div className="timeline">{[[Clock,'10:00','AM','賓客簽到','歡迎提早到場，與親友相聚、拍照留念，在我們為大家準備的飲品、小點與小遊戲中，共享美好時光。'],[Heart,'11:00','AM','戶外證婚','在綠意盎然的草地上，見證我們許下一生相伴的承諾。'],[Utensils,'12:30','PM','自助午宴','移步至帳篷宴會區，與我們一起享用自助午宴，分享這份喜悅。']].map(([Icon,time,period,title,desc])=>{const I=Icon as typeof Clock;return <article key={String(time)}><I strokeWidth={1}/><p className="time">{String(time)}<span>{String(period)}</span></p><h3>{String(title)}</h3><p>{String(desc)}</p></article>})}</div><p className="day-note">若有素食、食物敏感或其他飲食需要，歡迎在回覆出席時告訴我們。</p></section>
<section className="venue section" id="venue"><div><p className="eyebrow">03 / A PLACE TO CELEBRATE</p><h2>The White Barn HK</h2><p className="address"><MapPin size={18}/>新界元朗錦田水尾村 351 號</p><img className="mobile-only venue-mobile-photo" src={image('venue')} alt="The White Barn 的戶外草地證婚場地" loading="lazy"/><p className="venue-poem">草地、樹影與開闊的天空，<br/>是我們想與您分享的婚禮風景。</p><p className="pet-tag"><PawPrint size={16}/> 寵物友善場地 · 歡迎毛孩同行</p><a className="text-link" href={map} target="_blank" rel="noreferrer">在 Google Maps 查看路線 <ArrowUpRight size={17}/></a><div className="transport"><h3>交通安排</h3><div className="transport-item"><h4>接駁小巴</h4><p>免費接駁小巴將來往港鐵屯馬綫錦上路站 A 出口與 The White Barn，車程約 8 分鐘。班次、集合位置及時間將於婚禮前公布，請稍後留意我們的更新。</p></div><div className="transport-item"><h4>自駕泊車</h4><p>場地附近設有訪客停車場，免費車位數量有限。如需泊車，請於回覆出席時註明，以便我們預先安排。</p><a className="text-link" href="https://drive.google.com/file/d/1LVNlItoQ7qxwt3tMZGdCe_lhTx_DTuDx/view?usp=sharing" target="_blank" rel="noreferrer">查看私家車路線圖 <ArrowUpRight size={17}/></a><p>安全提示：如當天會飲酒，請安排其他交通方式，平安回家。</p></div><div className="transport-item"><h4>的士／Uber</h4><p>乘搭的士時，可告知司機前往「寵物樂園 Pet World Resort」或「錦田水尾村 351 號」；使用 Uber 時，搜尋上述名稱或地址即可。</p></div></div></div><div className="venue-visual"><img className="desktop-only" src={image('venue')} alt="The White Barn 的戶外草地證婚場地" loading="lazy"/><iframe title="The White Barn HK Google 地圖" src="https://maps.google.com/maps?q=The%20White%20Barn%20HK%20351%20Shui%20Mei%20Tsuen&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></section>
<section className="notes section" id="notes"><p className="eyebrow">04 / A FEW LITTLE NOTES</p><h2>讓這一天，更自在。</h2><div className="note-grid"><article><Leaf/><h3>草地上的穿搭</h3><p>歡迎以清新、輕便而得體的半正式服飾出席。證婚儀式將於戶外草地舉行，建議穿著平底鞋、粗跟鞋或坡跟鞋，避免幼跟及容易陷入草地的鞋款，讓大家能自在走動和拍照。</p></article><article><Sun/><h3>戶外的小準備</h3><p>二月戶外天氣可能較涼，建議帶備薄外套或披肩，並按需要準備防曬及防蚊用品。如遇雨天或天氣不穩，證婚儀式將移至場地的室內空間舉行。</p></article><article><Utensils/><h3>一起享用午宴</h3><p>婚宴為午間自助餐。若有素食、食物敏感或其他飲食需要，請在回覆時註明，讓我們提早與餐飲團隊協調。</p></article><article><PawPrint/><h3>毛孩也是家人</h3><p>場地寵物友善，歡迎帶毛孩來分享喜悅。如會帶同寵物出席，請於回覆時登記數目。按照場地規則，毛孩於場內須全程繫上牽繩，並請穿著禮貌褲，感謝大家的體諒與配合。</p></article></div></section>
<section className="memories"><figure className="desktop-only"><img src={image('joy')} alt="兩人在遊樂場滑梯上開懷大笑" loading="lazy"/></figure><figure><img src={image('market')} alt="Sophia 與 Kaiho 在傳統市集內合照" loading="lazy"/></figure></section>
<section className="rsvp section" id="rsvp"><div className="rsvp-intro"><p className="eyebrow">05 / RSVP</p><h2>這一天，<br/>希望有您在場。</h2><p className="desktop-only">每個家庭或同行組合只需提交一份回覆，讓我們為您和同行的家人或朋友作好安排。</p><p className="rsvp-deadline desktop-only">請於 2026 年 10 月 20 日前回覆，讓我們能提早為大家作好安排，謝謝。</p><p className="mobile-only rsvp-compact">請於 2026 年 10 月 20 日前回覆。<br/>每個家庭或同行組合填寫一份即可。</p><p className="fine desktop-only">如需更改已提交的回覆，可使用原先填寫時的裝置及瀏覽器重新填寫。如已轉用其他裝置或需要協助，歡迎直接聯絡我們。</p><img src={image('rsvp-snow')} alt="Sophia 與 Kaiho 在雪地上拿著婚禮日期牌" loading="lazy"/></div><form onSubmit={submit} className="rsvp-form">{done?<div className="success" role="status"><Check/><h3>收到您的心意了。</h3><p>{status}</p><button type="button" className="text-link" onClick={()=>{setDone(false);setStatus('')}}>修改回覆 <ArrowUpRight size={16}/></button></div>:<><div className="two-fields"><label>姓名 *<Input name="name" required maxLength={80} autoComplete="name" placeholder="方便我們稱呼您"/></label><label>WhatsApp 電話 *<Input name="phone" type="tel" required minLength={8} maxLength={24} autoComplete="tel" placeholder="例如 +852 9123 4567"/></label></div><fieldset><legend>您是哪一方的親友？ *</legend><Choices name="親友身份" value={side} onChange={setSide} options={['Kaiho（男家）','Sophia（女家）']}/></fieldset><fieldset><legend>您能出席我們的婚禮嗎？ *</legend><Choices name="出席意願" value={attend} onChange={setAttend} options={['出席','未能出席']}/></fieldset>{attend==='出席'&&<><fieldset><legend>出席環節 *</legend><Choices name="出席環節" value={events} onChange={setEvents} options={['證婚及午宴','只出席證婚','只出席午宴','稍後決定']}/></fieldset><div className="two-fields"><label>出席成人數目（包括自己） *<Input type="number" name="adults" defaultValue={1} min={0} max={30} step={1} required/></label><label>出席小童數目（包括嬰幼兒） *<Input type="number" name="children" defaultValue={0} min={0} max={30} step={1} required/></label></div><p className="fine">選擇「稍後決定」的親友，請日後更新參與環節。以上人數將用於您選擇的所有環節。如各環節人數不同，請在備註註明，讓我們跟進。</p><fieldset><legend>預計交通安排 *</legend><Choices name="預計交通安排" value={transport} onChange={setTransport} options={['自行前往','希望乘坐接駁車','自行駕車','尚未決定']}/></fieldset><label>同行毛孩數目<Input type="number" name="pets" defaultValue={0} min={0} max={10} step={1} required/></label><label>食物敏感或其他飲食需要<Textarea name="diet" maxLength={1000} placeholder="例如：1 位素食、1 位對花生敏感"/></label></>}<label>備註或想對我們說的話<Textarea name="note" maxLength={1500} placeholder="同行親友姓名、特別安排，或送給我們的祝福⋯⋯"/></label><div className="honeypot" aria-hidden="true"><label>Website<Input name="website" tabIndex={-1} autoComplete="off"/></label></div><label className="consent"><Checkbox checked={consent} onCheckedChange={v=>setConsent(Boolean(v))}/><span>我同意 Sophia 與 Kaiho 收集上述資料，僅用於婚禮出席統計及相關聯絡。回覆不會公開展示。</span></label>{status&&<p role="alert" className="error">{status}</p>}<button className="button submit" disabled={busy} type="submit">{busy?'正在確認您的回覆⋯':'送出回覆'}<ArrowUpRight size={18}/></button></>}</form><p className="fine mobile-only rsvp-update-help">如需更改已提交的回覆，可使用原先填寫時的裝置及瀏覽器重新填寫。如已轉用其他裝置或需要協助，歡迎直接聯絡我們。</p></section>
</main><footer><span className="signature">Sophia & Kaiho</span><p>20.02.2027 · THE WHITE BARN HK</p><p>期待，與您相見。</p><a href="#home">回到頂部 ↑</a></footer><nav className="mobile-bottom-nav" aria-label="手機段落導覽"><a href="#story"><Heart size={19}/><span>故事</span></a><a href="#day"><Clock size={19}/><span>流程</span></a><a href="#venue"><MapPin size={19}/><span>交通</span></a><a href="#notes"><Leaf size={19}/><span>須知</span></a><a href="#rsvp" className="bottom-rsvp"><Check size={19}/><span>回覆</span></a></nav></>;
}
